# mkdocs.yml

site_name: IBBI Documentation
site_url: https://ChristopherMarais.github.io/ibbi/
repo_url: https://github.com/ChristopherMarais/ibbi
repo_name: ChristopherMarais/ibbi
edit_uri: ""

theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: yes
            show_source: yes

nav:
  - Home: index.md
  - 'User Documentation':
    - 'Usage Guide': usage.md
  - 'API':
    - 'Reference': api.md
  - 'Development':
    - 'Contributing': CONTRIBUTING.md
    - 'License': LICENSE.md
