name: Publish Python Package to PyPI

on:
  release:
    types: [published, prereleased] # This workflow runs ONLY when you create a new GitHub Release.

jobs:
  pypi-publish:
    name: Build and publish package to PyPI
    runs-on: ubuntu-latest
    # The 'environment' and 'permissions' sections are commented out for token-based auth.
    # environment:
    #   name: pypi
    #   url: https://pypi.org/p/ibbi
    # permissions:
    #   id-token: write # Required for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for dynamic versioning from git tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Matches your environment.yml

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build package
        run: poetry build
        # The version will be automatically set from the Git tag by the plugin

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
